var ASCIIdata=
[
	{"DECIMAL": "00", "CHARACTER": "NUL", "DESCRIPTION": "Null"},
	{"DECIMAL": "01", "CHARACTER": "SOH", "DESCRIPTION": "Start of Heading"},
	{"DECIMAL": "02", "CHARACTER": "STX", "DESCRIPTION": "Start of Text"},
	{"DECIMAL": "03", "CHARACTER": "ETX", "DESCRIPTION": "End of Text"},
	{"DECIMAL": "04", "CHARACTER": "EOT", "DESCRIPTION": "End of Transmission"},
	{"DECIMAL": "05", "CHARACTER": "ENQ", "DESCRIPTION": "Enquiry"},
	{"DECIMAL": "06", "CHARACTER": "ACK", "DESCRIPTION": "Acknowledge"},
	{"DECIMAL": "07", "CHARACTER": "BEL", "DESCRIPTION": "Bell"},
	{"DECIMAL": "08", "CHARACTER": "BS", "DESCRIPTION": "Backspace"},
	{"DECIMAL": "09", "CHARACTER": "HT", "DESCRIPTION": "Horizontal Tab"},
	{"DECIMAL": "10", "CHARACTER": "LF", "DESCRIPTION": "Line Feed"},
	{"DECIMAL": "11", "CHARACTER": "VT", "DESCRIPTION": "Vertical Tab"},
	{"DECIMAL": "12", "CHARACTER": "FF", "DESCRIPTION": "Form Feed"},
	{"DECIMAL": "13", "CHARACTER": "CR", "DESCRIPTION": "Carriage Return"},
	{"DECIMAL": "14", "CHARACTER": "SO", "DESCRIPTION": "Shift Out"},
	{"DECIMAL": "15", "CHARACTER": "SI", "DESCRIPTION": "Shift In"},
	{"DECIMAL": "16", "CHARACTER": "DLE", "DESCRIPTION": "Data Link Escape"},
	{"DECIMAL": "17", "CHARACTER": "DC1", "DESCRIPTION": "Device Control 1"},
	{"DECIMAL": "18", "CHARACTER": "DC2", "DESCRIPTION": "Device Control 2"},
	{"DECIMAL": "19", "CHARACTER": "DC3", "DESCRIPTION": "Device Control 3"},
	{"DECIMAL": "20", "CHARACTER": "DC4", "DESCRIPTION": "Device Control 4"},
	{"DECIMAL": "21", "CHARACTER": "NAK", "DESCRIPTION": "Negative Acknowledge"},
	{"DECIMAL": "22", "CHARACTER": "SYN", "DESCRIPTION": "Synchronize"},
	{"DECIMAL": "23", "CHARACTER": "ETB", "DESCRIPTION": "End of Transmission Block"},
	{"DECIMAL": "24", "CHARACTER": "CAN", "DESCRIPTION": "Cancel"},
	{"DECIMAL": "25", "CHARACTER": "EM", "DESCRIPTION": "End of Medium"},
	{"DECIMAL": "26", "CHARACTER": "SUB", "DESCRIPTION": "Substitute"},
	{"DECIMAL": "27", "CHARACTER": "ESC", "DESCRIPTION": "Escape"},
	{"DECIMAL": "28", "CHARACTER": "FS", "DESCRIPTION": "File Separator"},
	{"DECIMAL": "29", "CHARACTER": "GS", "DESCRIPTION": "Group Separator"},
	{"DECIMAL": "30", "CHARACTER": "RS", "DESCRIPTION": "Record Separator"},
	{"DECIMAL": "31", "CHARACTER": "US", "DESCRIPTION": "Unit Separator"},
	{"DECIMAL": "32", "CHARACTER": "space", "DESCRIPTION": "Space"},
	{"DECIMAL": "33", "CHARACTER": "!", "DESCRIPTION": "exclamation mark"},
	{"DECIMAL": "34", "CHARACTER": "\"", "DESCRIPTION": "double quote"},
	{"DECIMAL": "35", "CHARACTER": "#", "DESCRIPTION": "number"},
	{"DECIMAL": "36", "CHARACTER": "", "DESCRIPTION": ""},
	{"DECIMAL": "37", "CHARACTER": "", "DESCRIPTION": ""},
	{"DECIMAL": "38", "CHARACTER": "", "DESCRIPTION": ""},
	{"DECIMAL": "39", "CHARACTER": "", "DESCRIPTION": ""},
	{"DECIMAL": "40", "CHARACTER": "", "DESCRIPTION": ""},
	{"DECIMAL": "41", "CHARACTER": "", "DESCRIPTION": ""},
	{"DECIMAL": "42", "CHARACTER": "", "DESCRIPTION": ""},
];