var decimalCtrl = -1
var decimalPrint = 31
var ASCII = "&#"

var ASCIIprintableData=
[
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": "space"},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": ASCII.concat(decimalPrint.toString())},
	{"DECIMAL": ""						   , "HEX": "" 						 , "CHARACTER": ""},
	
];

var ASCIIcontrolData=
[
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "NUL", "DESCRIPTION": "Null"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "SOH", "DESCRIPTION": "Start of Heading"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "STX", "DESCRIPTION": "Start of Text"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "ETX", "DESCRIPTION": "End of Text"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "EOT", "DESCRIPTION": "End of Transmission"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "ENQ", "DESCRIPTION": "Enquiry"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "ACK", "DESCRIPTION": "Acknowledge"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "BEL", "DESCRIPTION": "Bell"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "BS", "DESCRIPTION": "Backspace"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "HT", "DESCRIPTION": "Horizontal Tab"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "LF", "DESCRIPTION": "Line Feed"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "VT", "DESCRIPTION": "Vertical Tab"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "FF", "DESCRIPTION": "Form Feed"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "CR", "DESCRIPTION": "Carriage Return"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "SO", "DESCRIPTION": "Shift Out"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "SI", "DESCRIPTION": "Shift In"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "DLE", "DESCRIPTION": "Data Link Escape"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "DC1", "DESCRIPTION": "Device Control 1"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "DC2", "DESCRIPTION": "Device Control 2"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "DC3", "DESCRIPTION": "Device Control 3"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "DC4", "DESCRIPTION": "Device Control 4"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "NAK", "DESCRIPTION": "Negative Acknowledge"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "SYN", "DESCRIPTION": "Synchronize"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "ETB", "DESCRIPTION": "End of Transmission Block"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "CAN", "DESCRIPTION": "Cancel"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "EM", "DESCRIPTION": "End of Medium"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "SUB", "DESCRIPTION": "Substitute"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "ESC", "DESCRIPTION": "Escape"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "FS", "DESCRIPTION": "File Separator"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "GS", "DESCRIPTION": "Group Separator"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "RS", "DESCRIPTION": "Record Separator"},
	{"DECIMAL": (++decimalCtrl).toString(), "HEX": decimalCtrl.toString(16), "CHARACTER": "US", "DESCRIPTION": "Unit Separator"},
	{"DECIMAL": (++decimalPrint).toString(), "HEX": decimalPrint.toString(16), "CHARACTER": "DEL", "DESCRIPTION": "Delete"},
];

